### ISSUE TITLE
New theme with moving comment is distracting and hurts eyes and white lettering too bright 

### ISSUE THREAD

**Issue by billys41** [ytmous/ytmous#34]
how do I use old theme in the new ytmous

**Comment by Yonle** [comment]
Like, what

**Comment by billys41** [comment]
put back old theme the moving comments while watching video is distracting

**Comment by Yonle** [comment]
Old theme like what?
The one with ytmous logo and title at the navbar?

**Comment by billys41** [comment]
ya. i feel like it was darker, but i don't remember, this one hurts my eyes

**Comment by Yonle** [comment]
If you have your own ytmous server:
- There are instructions on README.md to let you modify the frontend page
- You could start editing files in `local` and change the frontend code as you wishes.

The reason why i switched away from bootstrap is due to complex code for such clean UI, Making a feature on frontend is not an easy task and always resulting a ugly result.

If you mean you want me to bring back the old frontend to the upstream, Then that will never happend due to the given reason above. 

---
You could still revert to the commit of where the old UI is still being used, But note that we are no longer using ytdl-core, ytsr, and ytpl as the dependencies. Any issues related to error on dependencies in older version of ytmous will not be tolerated.

**Comment by Yonle** [comment]
Most importantly, Reduce your screen brightness.
